### ISSUE TITLE
Call to undefined method soapclient::__setSoapHeaders(). How do I install the soap client here?

### ISSUE THREAD

**Issue by sonesay** [esimonetti/SugarDockerized#66]
[Wed Jun 12 04:19:19.467242 2019] [php7:notice] [pid 15] [client 172.19.0.1:34448] PHP Fatal error:  Uncaught Error: Call to undefined method soapclient::__setSoapHeaders() in /var/www/html/modules/Connectors/connectors/sources/ext/soap/marketoisu/marketoisu.php:213\nStack trace:\n#0 /var/www/html/include/connectors/sources/SourceFactory.php(39): ext_soap_marketoisu->init()\n#1 /var/www/html/include/connectors/ConnectorFactory.php(28): SourceFactory::getSource('ext_soap_market...')\n#2 /var/www/html/include/connectors/ConnectorManager.php(39): ConnectorFactory::getInstance('ext_soap_market...')\n#3 /var/www/html/include/connectors/ConnectorManager.php(104): ConnectorManager->buildConnectorsMeta()\n#4 /var/www/html/clients/base/api/ConnectorApi.php(57): ConnectorManager->getUserConnectors()\n#5 /var/www/html/include/api/RestService.php(268): ConnectorApi->getConnectors(Object(RestService), Array)\n#6 /var/www/html/api/rest.php(23): RestService->execute()\n#7 {main}\n  thrown in /var/www/html/modules/Connectors/connectors/sources/ext/soap/marketoisu/marketoisu.php on line 213, referer: http://docker.local/

**Comment by esimonetti** [comment]
I would recommend to leverage the local stacks, so that you can modify them according to your specific needs and install the additional libraries you require. An example is: https://github.com/esimonetti/SugarDockerized/blob/master/stacks/sugar9/php73-local-build.yml that will build the images based on the docker file (https://github.com/esimonetti/SugarDockerized/blob/master/images/php/73/apache/Dockerfile) and obey your changes you might have completed in there.
Obviously you would have to repeat those changes when you pull the latest changes from this repository, but at least it gives you an immediate way forward.

Hope it helps
